language: python
before_install:
- pip install pycodestyle
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=artellapipe
- sphinx-apidoc -f -e -o docs/sphinx artellapipe
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: 0CFNuyA3UBDduL5c1u73pKuNUdjvaVINogtTVLbgu3fliq6MlgRoD+8+FVQWhA2ZJKp33kzVYSUTsFzSpERNHLmqynmWFzd9rV+M1m25dEUoEEv6nj22d2aeHtAUiysvw4cl/b84M18GO3YmnYHJtZ/71m0jFKAPWScWGXOcKlqNhbMKnoGAhbmO8Lpx06FZpqrBvHnGJUhS4t/NrbjAqELx1AJ59MKRW1P9nDcNPEDS3E3c+hk0YY3byrGEw+YVt7cyk8D6e9rJTzPHFviU83jhoLlKfQspEs10nZbZH1gVsco9iEyXoChvJC44KgmCRUULtHaT7Kpmdjt09nOJK53FJU33XAF8aBrYOnvCooF3uYvMeLiMduPKzmcjhqyBgVzY+iUMSqjdshxZkrdiJozskG5J54DJEP2pcQDl9CzgpqKTQ82GUZKacI/Bbaut8S+TlLvoUFbWAarL8A1GkKD+Xcr9YbviKubgFIyrNvYWaWUZDZ0ocIL+csuaXTgVN80RdqWdTwli0SZ/FblumF0D6bMWHqwXENEJcP4kEjDZ7QQmxCfRDh/67Fcrg/6T/WMi0DRXTbASiuFwF6/9uuaS8mCVo5IZOx7rdz+PQFrxXFuQ338FshcA4Pwf2BBXweRJdK9CMQsy48vG0UNYuO7ZskPLXLXYqLrAV61BIDo=
    on:
      branch: master
      tags: true